apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zah5kfy3a-go
  janus-idp.io/tekton: zah5kfy3a-go
  backstage.io/kubernetes-id: zah5kfy3a-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zah5kfy3a-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
